require('plugins/main')
require('settings/main')
require('settings/_keymapping')
require('plugins/_sonokai')
require('plugins/_nvimtree')
require('plugins/_lualine')
require('plugins/_lspconfig')
require('plugins/_bufferline')
require('plugins/_autopairs')
require('plugins/_autocmp')
require('plugins/_treesitter')
require('plugins/_telescope')
require('plugins/_trouble')
require('plugins/_null-ls')
-- require('plugins/_lspsaga-config')
